### ISSUE TITLE
Support dynamic config reloading

### ISSUE THREAD

**Issue by alkalinecoffee** [tricksterproxy/trickster#12]
It would be nice if Trickster supported dynamic reloading of the config file (similar to Prometheus' `POST /-/reload` endpoint or via kill signal).  This is useful when using consul-template for pushing configs dynamically.

**Comment by pcarranza** [comment]
I'm thinking that it would be enough with just reloading the origins from the configuration file on SIGHUP as a first step.

Reloading ports would include bouncing the server, and that may be too much.

Would it make sense as a first approach?

**Comment by jranson** [comment]
I am working on this at https://github.com/jranson/trickster/tree/config-reload and have it working but not tested beyond confirming a kill -HUP <pid> will trigger the config reload, and the reloaded origins are respected. I would appreciate any help testing out to ensure it is otherwise safe!

**Comment by sylr** [comment]
You can also implement fsnotify so you don't need external action to reload config.

https://github.com/jimmidyson/configmap-reload/blob/master/configmap-reload.go#L46-L75

**Comment by SuperQ** [comment]
I would prefer the standard convention of active reloading. Automatic reloading can be touchy if the config is reloaded in the middle of a file write. So you end up having to always do atomic writes, which means if you're just using a text editor to tweak a config, it now becomes much more complicated.

**Comment by jranson** [comment]
All, at long last, v1.1 is released and includes the config reload feature, which you can read about [here](https://github.com/tricksterproxy/trickster/blob/master/docs/configuring.md#reloading-the-configuration). Enjoy!
