### ISSUE TITLE
Trickster with PVC filesystem cache doesn't proxy after pod-recreation

### ISSUE THREAD

**Issue by shaikatz** [tricksterproxy/trickster#372]
Hi,

While using trickster with PVC and filesystem cache, when the pod is recreated (in case of node scale-down or pod eviction) the new pod doesn't answer to any queries although it still creates new cache files in the cache folder.

I can't see anything relevant in the pod debug logs.

**Comment by LimitlessEarth** [comment]
What version of the chart are you using? Sorry so much of this is in flux. 

To make sure I understand, the pod runs and is writing stuff out onto the PVC but it isn't giving you data back? If so what sort of response do you get?

**Comment by shaikatz** [comment]
I'm using the chart from my helm fixes PR.
I don't think it's related to the setup, the behavior is that on the first lunch of the pod when the PVC is empty, everything is working correctly.
After the pod being recreated, it uses the same PVC, but now the requests just getting timed out.
You can try to reproduce that easily.

**Comment by jranson** [comment]
@shaikatz we have pushed release [v1.0.2](https://github.com/tricksterproxy/trickster/releases/tag/v1.0.2) that hopefully fully addresses this. If you wouldn't mind giving it a try and let us know if it resolves for you, that would be great. Thanks!

**Comment by shaikatz** [comment]
Hi @jranson, unfortunately continue the adoption of trickster dropped in priority for me, so I won't be able to do it soon.
I'll close the issue and re-open if necessary.
