### ISSUE TITLE
Windows release/support?

### ISSUE THREAD

**Issue by codywilliams5** [tricksterproxy/trickster#383]
Apologies if incorrect place for this, but any plans for Windows x64 release? Prometheus/loki/the rest have windows releases. Want to have trickster bad but its a Windows server only environment (I know...)

Or at least support for building on Windows? I tried setting up a go environment and building but eventually go starts complaining about *nix dependencies.

**Comment by jranson** [comment]
@codywilliams5 this is the right place, and windows binaries are a great idea for future releases. There are currently 2 unix package dependencies for the filesystem cache, which are resulting in the compilation issues you encountered. Those should be fairly easy to swap out for something more generic, but it means we won't be able to provide windows binaries for past releases. Trickster v1.1 will be released by the end of the month, so be sure to add yourself as a watcher for releases so you will know as soon as it's available, including a win64 binary.

**Comment by codywilliams5** [comment]
@jranson What excellent news! As a potential new user past releases are no worry for us. I look forward to Trickster 1.1, and I'll put it through its paces in a significant production windows environment xD Thanks to you, your team, and Comcast for sharing what looks like a very excellent project.

**Comment by jranson** [comment]
hey @codywilliams5  - sorry for the extended time on this one. We have released the first beta of Trickster v1.1, and have included our first ever win64 binary in the [v1.1.0-beta1 Release](https://github.com/tricksterproxy/trickster/releases/tag/v1.1.0-beta1) distribution. Two areas where we would love some feedback. First, does it work without any issues in your environment? And secondly, are the [Windows-specific default values](https://github.com/tricksterproxy/trickster/blob/master/pkg/config/defaults/defaults_windows.go) solid, or can we improve them before the end of the beta cycle? Thanks so much for this feature request and for the assist in getting it GA'd!

**Comment by codywilliams5** [comment]
@jranson No need to apologize, its a crazy year and its open source anyway! Thank you for considering my request. 

Configured Trickster today. Straight forward. No issues so far. Moved a few dashboards to it (apparently Grafana doesn't support easy source changes if you don't use variables to start so its a bit manual). I need to move a few more dashes to put it in some more production use. Had some differences at first but I realize its due to fast forward which is configurable. Prometheus cpu use already down. Looking good. I'll push more onto it and see how it holds up. 

The default values look decent at first glance. I'm passing a config for now. I tried switching to cache_type = 'filesystem' to test the default location but its booting as memory anyway. Maybe that means the default is inaccessible, but maybe I'm missing another config value. Too early to tell and didn't have much time to play today. So I have to try and find some time to play with the default values a bit more.

**Comment by codywilliams5** [comment]
@jranson Filed issue #424, the default paths are indeed not working right. I can't test the systems other then mem and filesys for you as I don't use them. Otherwise so far so good trickster holding up well in production as promcache.

**Comment by jranson** [comment]
v1.1, which includes the win64 binary support, is released. Thanks for this feature request!
