### ISSUE TITLE
[Feature request] Config check

### ISSUE THREAD

**Issue by rlex** [tricksterproxy/trickster#393]
Hello! I wrote [ansible role for trickster](https://github.com/rlex/ansible-role-trickster)

However, there is no config check command which will be really nice to check for errors in config before restarting (toml is very easy to fuck up)

It will be nice to have something like 
```
trickster -config-check /etc/trickster.conf
```
Which returns either 0 if checks passed or anything but not 0 in case it fails.

**Comment by jranson** [comment]
Thanks for your awesome extension to our project (!!) and for this great and timely request.

We definitely need to have a config check feature. While Trickster runs many checks at startup to validate the config, they are not quite in a state that is conducive for a dry-run-style config check. But they are close.

We are finally putting real work into #12 on in the v1.1.x branch, and definitely need the config check for the in-process config reload feature. When Trickster is running with a good config, and the underlying config file is refreshed, we will need to validate the refreshed configuration before applying it to the process, and issue a warning/abort if it does not. So we'll be getting this sorted out over the next couple of weeks, and will make sure to also enable the dry-run option via a command-line argument.

**Comment by jranson** [comment]
hey @rlex - we have released Trickster 1.1.0-beta1, which includes the config check feature. We'd really love it if you gave it a try and provided any new feedback before we end the beta cycle. You can even download the binaries tarball from the [1.1.0-beta1 Release](https://github.com/tricksterproxy/trickster/releases/tag/v1.1.0-beta1) and run it locally against any config you have to test with. 

Example usage:

```toml
.trickster -validate-config -config /path/to/toml/trickster.conf
```

**Comment by rlex** [comment]
Sorry for delay. I'll test it next week.

**Comment by jranson** [comment]
v1.1 is released and includes the config validation feature. Thanks for the input, enjoy!
