### ISSUE TITLE
Error in example config

### ISSUE THREAD

**Issue by rlex** [tricksterproxy/trickster#394]
Example config in sample_rate var (https://github.com/Comcast/trickster/blob/master/cmd/trickster/conf/example.conf#L452) states that
```
sample_rate = 1
```
Can be used. However, if launched with that setting, trickster will crash due to failed conversion of int64 to go float.

Setting sample_rate to 1.0 allows trickster to launch.

**Comment by jranson** [comment]
Thanks for this report, I just committed a change to master for the main example.conf. We'll push a corresponding helm/kube/etc update to those projects with the next release. I'll keep this issue open until those changes are also made.

**Comment by jranson** [comment]
This change has been fully propagated and released. Thank you for the report and the associated PR!
