### ISSUE TITLE
prometheus quantile_over time slow responce

### ISSUE THREAD

**Issue by vishnubraj** [tricksterproxy/trickster#409]
I  just installed trickster between Grafana and Thanos server. 
The quantile_over_time  requests takes longer time to execute in Thanos. but tricster also it takes the same amount of time. is it expected because the actual calculation runs on the Thanos server?

Thanos results:

```
[:vishnu:root@opstest1.sjc2 ~]# curl -g -o /dev/null -s  -w "test_victoria_smallsample %{time_starttransfer}\n" http://192.168.102.200:19190/'api/v1/query?query=quantile_over_time(0.95,(rate(ifHCOutOctets{ifAlias=~"pl3.*|pl2.*|tl3",instance=~".*"}[5m])*8)[30d:])&time=1586420555'
test_victoria_smallsample 16.580
[:vishnu:root@opstest1.sjc2 ~]#
```
Trickster result
```
[:vishnu:root@opstest1.sjc2 ~]# curl -g -o /dev/null -s  -w "test_victoria_smallsample %{time_starttransfer}\n" http://localhost:5555/'api/v1/query?query=quantile_over_time(0.95,(rate(ifHCOutOctets{ifAlias=~"pl3.*|pl2.*|tl3",instance=~".*"}[5m])*8)[30d:])&time=1586420555'
test_victoria_smallsample 16.422

```

**Comment by jranson** [comment]
When you execute the query against Trickster the first time you can expect it to be about the same execution time as a direct query, as in your example, because no data for that query is in the Trickster cache. It is the second, third, and beyond queries via Trickster that should be very fast.

**Comment by vishnubraj** [comment]
no @jranson  subsequent queries also taking the same time.. i did query multiple times and received the same response time.

**Comment by vishnubraj** [comment]
i think this formuala in run in thanos.. and thanos collects data from sidecars and calculates the results and sends the result value so trickster doesnt know about the time series data. correct me if i am wrong.

Also i believe trickster cannot be installed between thanos querier and side car also .
