### ISSUE TITLE
Windows Default Paths Incorrect Bevahior

### ISSUE THREAD

**Issue by codywilliams5** [tricksterproxy/trickster#424]
Default paths are listed as:
	DefaultCachePath = `%TEMP%\trickster`
	DefaultConfigPath = `%APPDATA%\trickster\trickster.conf`

The %ENVVARIABLES% should resolve to local user directories. For example, the config path resolves in Windows to me as: C:\Users\MyUser\AppData\Roaming\trickster\trickster.conf. 

Trickster does not do this. Trickster checks for a full path in its working directory. For example if I run 'C:\Program Files\Trickster\trickster-1.1.0-beta1.windows-amd64.exe' it expects a temp file to be at 'C:\Program Files\Trickster\%APPDATA%\trickster\trickster.conf', and if i provide that files and use filesystem cache without a specified directory the cache will be created at 'C:\Program Files\Trickster\%TEMP%\trickster'.

Yuck for some reason github is butchering some of the paths above. Its cutting the \ between trickster and the % folder names. I'll attach a screenshot below for clarity. 

Expected behavior: properly resolve those directory names.

Alternate expected behavior: Most go software in this world (prometheus, importers, etc) would just use the working directory for everything. IE look for trickster.conf in the launch directory and create a '\cache' in the working directory. I don't want to speak for all windows admins but that might be a more expected behavior and would be an easy fix to this issue. 

![image](https://user-images.githubusercontent.com/42254951/81724754-be998400-9439-11ea-9cad-3ed5750bcb32.png)

**Comment by jranson** [comment]
hey cody could you take a look at https://github.com/tricksterproxy/trickster/pull/426/files and elt me know if that looks alright. Since ENV is not being interpolated by default, I would prefer we just stick to the basic file glob support and default to `.` as you recommend. Thanks for the feedback!

**Comment by jranson** [comment]
@codywilliams5 we went ahead and merged the previously-mentioned PR ^^^ so that we can get Beta3 out the door. If you can give that a try when you have a chance we'd really appreciate the help. Thanks again!

**Comment by jranson** [comment]
fixed in v1.1
