### ISSUE TITLE
caching empty results

### ISSUE THREAD

**Issue by rrusso1982** [tricksterproxy/trickster#435]
I have some metrics that do not necessarily show up into prometheus in a timely fashion.  Sometimes a minute or two after they were created as that is when they become available at the target endpoint.  With trickster in the query path I am caching empty buckets for those period where the metrics are missing even though the metric show up some time later in prometheus.

Is their either a way to not cache an empty result bucket or to flag some query strings as not cachable?

**Comment by jranson** [comment]
hey Rob, thanks for using Trickster and hitting us up about this.

we have a solution for this exact situation, where there is a delay in the results coming in to prometheus (or any other tsdb that trickster accelerates), and so timestamps within a relative window of real time should not be cached . it's an origin configuration called Backfill Tolerance, that gives the origin some extra time to settle on a final value for those newer timestamps before trickster caches them. it works by trimming datasets down just before caching, such that timestamps newer than `now() - $backfill_tolerance_secs` are excluded from the cache. most users find a value of 120, 180 or 300 seconds works great, depending upon the degree of latency from the original telemetry source.

While it is currently an origin config, we are working to make features such as this one, available on a per-query basis using comments in the query string to trigger the feature; so stay tuned for that in a future release as well. 

For now, `backfill_tolerance_secs` and can be used as follows:
```toml
[origins]
  [origins.default]
  origin_type = 'prometheus'
  origin_url = 'http://prometheus:9090'
  cache_name = 'default'
  backfill_tolerance_secs = 180
```

If you are using a version of Trickster earlier than 1.0, this setting exists under a different name and I am happy to dig that out for you, just let me know.

**Comment by rrusso1982** [comment]
thats great.  I'll give it a try.  thanks

**Comment by jranson** [comment]
@rrusso1982 just wanted to check and see if this proposed solution hooked you up. Thanks for letting us know!

**Comment by rrusso1982** [comment]
> @rrusso1982 just wanted to check and see if this proposed solution hooked you up. Thanks for letting us know!

Yes this was exactly what I needed.  Thanks for all the help.
