### ISSUE TITLE
v1.1.0: invalid memory address or nil pointer derefernce

### ISSUE THREAD

**Issue by bsnyder788** [tricksterproxy/trickster#452]
```panic: runtime error: invalid memory address or nil pointer dereference	
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x9bccd0]	
goroutine 45612 [running]:	
github.com/tricksterproxy/trickster/pkg/proxy/engines.DeltaProxyCacheRequest.func2(0xc001a375b0, 0xcc7380, 0xc0012f43c0, 0xc003dfe840, 0xc000182690, 0x7fa561d51e18, 0xc000175300, 0xc003f47930, 0xc002e70ab0, 0xc003f47890, ...)	
/home/runner/work/trickster/trickster/pkg/proxy/engines/deltaproxycache.go:352 +0x280	
created by github.com/tricksterproxy/trickster/pkg/proxy/engines.DeltaProxyCacheRequest	
/home/runner/work/trickster/trickster/pkg/proxy/engines/deltaproxycache.go:344 +0x1c70	```

**Comment by jranson** [comment]
Thanks for reporting! We'll get this root-caused and corrected today with a patch release.

**Comment by bsnyder788** [comment]
Awesome, thank you!

**Comment by jranson** [comment]
@bsnyder788 we have cut that release `v1.1.1`, which has a nice ring to it. Thanks again for this report, and let me know if this mitigates the issue for you and we'll close out the issue.

**Comment by jranson** [comment]
@bsnyder788 just wanted to check with you on this issue and if v1.1.1 (or now .2) has resolved this for you? Thanks again for reporting and letting us know. have a great weekend!

**Comment by bsnyder788** [comment]
v1.1.1 has been working great for me.  Been up 17 days with no panics, etc.

**Comment by jranson** [comment]
Great, thanks for letting us know! We always appreciate the great feedback from the DO team. I'll go ahead and close this issue out.
