### ISSUE TITLE
Influx Origin Wait Group Panic

### ISSUE THREAD

**Issue by disfluxly** [tricksterproxy/trickster#463]
Deployed Trickster 1.1.2 out to AWS Fargate via the official docker image. The process seems to be randomly dying as I haven't noticed any kind of pattern. Here's the logs information:

```
panic: sync: WaitGroup is reused before previous Wait has returned
goroutine 1100028 [running]:
sync.(*WaitGroup).Wait(0xc00056dac0)
/opt/hostedtoolcache/go/1.14.3/x64/src/sync/waitgroup.go:132 +0xad
github.com/tricksterproxy/trickster/pkg/proxy/origins/influxdb.(*SeriesEnvelope).Sort.func1(0xc000186800, 0xc00056db58, 0xc00056dac0, 0x0, 0xc00056da78, 0xc000406240, 0xc00056db50, 0xc00056dbe0, 0x0)
/home/runner/work/trickster/trickster/pkg/proxy/origins/influxdb/series.go:462 +0x2a1
created by github.com/tricksterproxy/trickster/pkg/proxy/origins/influxdb.(*SeriesEnvelope).Sort
/home/runner/work/trickster/trickster/pkg/proxy/origins/influxdb/series.go:437 +0x1f8
```

Here's my config:

```
[frontend]
listen_port = 8480

[caches]
	[caches.default]
	cache_type = 'memory'

[origins]
	[origins.default]
	origin_type = 'influxdb'
	origin_url = http://myinfluxinstance
	forwarded_headers = 'both'
	backfill_tolerance_secs = 300

[tracing]
	[tracing.default]
	tracer_type = 'jaeger'
	collector_url = 'localhost:6831'
		[tracing.default.jaeger]
		endpoint_type = 'agent'
```

**Comment by disfluxly** [comment]
@jranson  - Sorry to ping you directly, but any idea on this?

**Comment by jranson** [comment]
Hi @disfluxly sorry we have not taken a look at this just yet, but we will this week. WaitGroup errors are definitely always a bug, so thanks for this report. I will follow up on this issue once we have it fixed up.

**Comment by jranson** [comment]
@disfluxly thanks again for reporting this. We have identified the cause of this issue and will have the fix included in v1.1.3 that should be cut later this week. Thanks for your patience!

**Comment by jranson** [comment]
(ditto on this one!)

**Comment by disfluxly** [comment]
This one is a bit harder to test from local as it was only visible under decent traffic conditions (at least in my env). Deploying it and I'll let you know next week.

**Comment by disfluxly** [comment]
I haven't seen this panic at all this week in testing, going to close this one. I'm gonna open up another issue for a question/documentation
