### ISSUE TITLE
Influx Origin Multi Statement Query Displaces Series Data

### ISSUE THREAD

**Issue by disfluxly** [tricksterproxy/trickster#464]
Trickster 1.1.2, deployed to AWS Fargate using the official Docker Image.

Initial cache build query seems to work fine, but then any of the "accelerated" queries seems to:

1. Add the data to a single statement results, even with multiple queries
2. Adds the data to the _wrong_ statement results

In the example below, the second statement gets returned by Trickster with the values from the first statement.

Real Data:
![image](https://user-images.githubusercontent.com/31159882/86930707-4b448380-c105-11ea-9ee5-360913f2bb17.png)

Trickster Data:
![image](https://user-images.githubusercontent.com/31159882/86930754-59929f80-c105-11ea-9896-11dbdb58f08b.png)

Trickster Conf:
```
[frontend]
listen_port = 8480

[caches]
	[caches.default]
	cache_type = 'memory'

[origins]
	[origins.default]
	origin_type = 'influxdb'
	origin_url = http://myinfluxinstance
	forwarded_headers = 'both'
	backfill_tolerance_secs = 300

[tracing]
	[tracing.default]
	tracer_type = 'jaeger'
	collector_url = 'localhost:6831'
		[tracing.default.jaeger]
		endpoint_type = 'agent'
```

Additionally, inspecting the query results back shows that there are two series, but it only grabs latest values for one of the queries back, and adds them to the _wrong_ result set. Here's a shortened example:

```
{
  "results": [
    {
      "statement_id": 0,
      "series": [
        {
          "name": "Binder.product.overall.status.family",
          "columns": [
            "time",
            "mean"
          ],
          "values": [
            [
              1594216980000,
              59.186982916666665
            ],
            [
              1594217010000,
              59.245457625
            ],
            [
              1594217040000,
              58.25713816666667
            ],
            [
              1594217070000,
              64.62424958333334
            ],
            [
              1594217100000,
              71.86223350000002
            ],
            [
              1594217130000,
              64.00148116666665
            ],
            [
              1594217160000,
              160.6153846153846
            ],
            [
              1594217190000,
              201.69230769230768
            ],
            [
              1594217220000,
              214.51282051282053
            ],
            [
              1594217250000,
              223.87179487179486
            ],
            [
              1594217280000,
              208.33333333333334
            ],
            [
              1594217310000,
              193.07692307692307
            ],
            [
              1594217340000,
              197.05128205128204
            ],
            [
              1594217370000,
              193.82051282051282
            ],
            [
              1594217700000,
              61.828707
            ]
          ]
        }
      ]
    },
    {
      "statement_id": 1,
      "series": [
        {
          "name": "Binder.product.overall.status.family",
          "columns": [
            "time",
            "mean"
          ],
          "values": [
            [
              1594217010000,
              195.07692307692307
            ],
            [
              1594217040000,
              184.56410256410257
            ],
            [
              1594217070000,
              177.23076923076923
            ],
            [
              1594217100000,
              173.69230769230768
            ],
            [
              1594217130000,
              156.35897435897436
            ]
          ]
        }
      ]
    }
  ]
}
```

Notice how statement 1 ENDS at timestamp `1594217130000`. While statement 0 has values that continue past that timestamp. All values that continue past that timestamp _should_ have been attributed to statement 1, which you can identify by the screenshots above and the sudden jump in the value.

**Comment by disfluxly** [comment]
@jranson  - Also this one :)

**Comment by jranson** [comment]
@disfluxly if you are able to provide an example query for this so that we can reproduce, that would be great. Thank you!

**Comment by disfluxly** [comment]
@jranson - One better, here's a full docker-compose setup:

https://github.com/disfluxly/trickster_docker_compose

Once you spin it up, wait for a few minutes for telegraf to add some data, then go to `http://localhost:3000`. Default grafana login. Create the `Internal` dashboard via the `internal.json` file in the repo, and then head to that dashboard. You'll see multiple metrics on the dashboards at first, but as Trickster queries for new data, the return statement will only have series data for the last series queried. Since it only returns 1 series, Grafana will begin plotting the rest of the data for whatever metric was actually the first series. It should become pretty clear quickly once you see it.

**Comment by disfluxly** [comment]
BTW, this looks to be partially a result of the change for 1.1.2. However, 1.1.1 is broken as well, in that it _only_ returns the last series queried regardless of whether or not its part of the accelerated query.

**Comment by jranson** [comment]
We have this one all root caused and fixed up, thanks again for the detailed report and the test artifacts, we really appreciate it! Will be included in v1.1.3

**Comment by disfluxly** [comment]
Happy to help!

**Comment by jranson** [comment]
@disfluxly this release has been cut and we'd really appreciate if you can confirm this issue is resolved for you. Thanks!

**Comment by disfluxly** [comment]
This one looks good!
