### ISSUE TITLE
Update Jquery version in Trickster to greater than 3.5.0

### ISSUE THREAD

**Issue by envy7** [tricksterproxy/trickster#485]
Hi team, we are using the latest container image available in dockerhub `tricksterio/trickster:latest`

Currently it seems trickster is using jquery 3.3.1. If I traverse the /graph endpoint I can see the below

>  <script src="/static/vendor/js/jquery-3.3.1.min.js?v=b90be6f32a33c03163d700e1452b54454ddce0ec"></script>

If possible please upgrade the jquery version being used to > 3.5.0. As this is getting flagged as vulnerable in PCI Audit Scans. You can find the vulnerabilities for jquery published here: https://snyk.io/vuln/npm:jquery. Jquery versions <3.5.0 are vulnerable to cross-site scripting attacks.

**Comment by jranson** [comment]
Hi @envy7 Trickster is a golang application and does not use jQuery (javascript). Trickster is a proxy, which means all static content (including javascripts) is served from an upstream source that it accessed on the caller's behalf (eg., a Prometheus backend, which does have a /graph endpoint). So if your systems are flagging Trickster as vulnerable, you will need to look at the backend origins and patch those.

**Comment by envy7** [comment]
Thanks for the information @jranson understood, will try to patch the prometheus backend instead.
