### ISSUE TITLE
[BUG] using "&add_http_cors_header=1" in origin type "clickchouse" always return `X-Trickster-Result: engine=HTTPProxy; status=proxy-only`

### ISSUE THREAD

**Issue by Slach** [tricksterproxy/trickster#487]
During figure out with trickster in https://github.com/Vertamedia/clickhouse-grafana/issues/281
i found when using "&add_http_cors_header=1" in origin type "clickchouse" then 
trickster always return `X-Trickster-Result: engine=HTTPProxy; status=proxy-only`

**Comment by jranson** [comment]
@Slach v1.1.3 addresses this issue if you don't mind giving it a spin for us. thanks for using Trickster!

**Comment by Slach** [comment]
thanks a lot for your efforts team ;)
