### ISSUE TITLE
Combining environment variables with a config file does not appear to honor environment variables

### ISSUE THREAD

**Issue by WesleyDavid** [tricksterproxy/trickster#490]
Trickster Version: 1.1.2

When attempting to build a trickster environment on-demand, my team attempted to use a combination of environment variables as well as a .conf file. However, it does not appear that there is any convergence of multiple configuration sources. It appears that if a configuration file is present, only the options chosen in the configuration file are honored, and there's no supplementing of any options that are only configured in environment variables.

For example, if there is no `origin_url = 'http://host:port'` in the configuration file, it was assumed that the value of `TRK_ORIGIN` would be used. However, it appears that is not the case. Even with a `TRK_ORIGIN` environment variable and no `origin_url` option supplied in the configuration file, it doesn't seem to be supplying the trickster process with any origin information.

When reading the [documentation](https://github.com/tricksterproxy/trickster/blob/main/docs/configuring.md), it appeared at first that a config while would be read, and then any options not supplied in the config file, but found in environment variables (or thirdly command line options) would be detected and then converged into the running config for the Trickster process. Upon re-reading, I can see that it may not be the case.

So I think this issue boils down to a few topics:

1. Am I understanding correctly that this is behaving as designed?
2. If #1 is correct, it would be awesome if the running configuration was converged from multiple sources.
3. It would be even more awesome if all possible configuration options were tunable via environment variables. :smile:

**Comment by WesleyDavid** [comment]
I believe I've committed a variant of the [X Y Problem](http://xyproblem.info/). [The documentation](https://github.com/tricksterproxy/trickster/blob/main/docs/configuring.md) refers to `TRK_ORIGIN`, however I believe it should be `TRK_ORIGIN_URL`. Then, without a proper `TRK_ORIGIN_URL`, it appears that loader.go won't even bother with pulling in `TRK_ORIGIN_TYPE`.

So at the moment, this is appearing to be a simple matter of a misnamed environment variable causing the most visible problem we were experiencing. I'll have a PR for the documentation fixup here in a moment!

**Comment by jranson** [comment]
Hey Wesley. The idea behind ENV and CLI is that they are _overrides_ to a functioning base config and are (currently) meant for very simple configurations that use a default origin. The base config file is checked for for completeness _before_ overlaying ENV and CLI values. So if the config file does not include an origin_url for the default origin, trickster should fail out at startup, even if you have provided one of the overlays. That means, so long as you put _something_ in the `origin_url` for the default origin, the overrides should work properly. Overrides only apply to the origin named `default` and the cache named `default`.

The 2.0 release will support overriding any value via ENV, similar to how it is implemented in Grafana, as well as sourcing multiple config files together (so you can have a common file, plus a customization file for a particular instance deployment). When we have functionality baked in, I'm definitely down for allowing the entire config to be run via ENV and flags. These enhancements probably won't make it into the first 2.0 beta, but it will be included before GA.

BTW, v1.1.3 was released just a few days ago; I would recommend upgrading, as it makes 2 significant fixes to InfluxDB stability and cached data integrity.

**Comment by WesleyDavid** [comment]
Great! Thanks for the clarity. Good to know and we can run with that.

> The 2.0 release will support overriding any/all values via ENV, similar to how it is implemented in Grafana, as well as sourcing multiple config files together (so you can have a common file, plus a customization file for a particular instance deployment).

That sounds like an absolute dream! Looking forward to it. (Grabbing v1.1.3 for testing in three, two, one...)
