### ISSUE TITLE
Documentation Cleanup

### ISSUE THREAD

**Issue by jranson** [tricksterproxy/trickster#495]
This issue is for anyone who is not a coder, since it is largely search and replace.

With Trickster 2.0, some of the naming conventions are being changed to share the same nomenclature as other cloud native projects. Much of the core code has already been updated, while references to the old names are still littered throughout the documentation, code comments, and example configurations. We need to update all of these. 

These are the heaviest hitters, but the assignee can always ask on this issue if they find others that should be updated.

Old Name | New Name
-----------|--------------
origin | backend
origin_type | provider
cache_type | provider

**Comment by pooja-gera** [comment]
Hi, can I please be assigned this?

**Comment by jranson** [comment]
Sure thing!  btw, one thing to note, for instances of `origin_url`, lets leave those as-is for now

**Comment by jranson** [comment]
origin_type updates needed:

```
./deploy/trickster-demo/docker-compose-data/trickster-config/trickster.conf
53:  origin_type = 'prometheus'
59:  origin_type = 'prometheus'
65:  origin_type = 'prometheus'
71:  origin_type = 'prometheus'
77:  origin_type = 'reverseproxycache'
--
./deploy/kube/configmap.yaml
262:        # origin_type identifies the origin type.
264:        # origin_type is a required configuration value
265:        origin_type = 'prometheus'
303:        ## This is only effective if the origin_type is 'rule'
465:        # origin_type = 'influxdb'
--
./docs/rule.md
97:  origin_type = 'rule'
101:  origin_type = 'rpc'
105:  origin_type = 'rpc'
--
./docs/paths.md
49:    origin_type = 'rpc'
121:    origin_type = 'rpc'
221:    origin_type = 'prometheus'
--
./docs/multi-origin.md
38:        origin_type = 'prometheus'
45:        origin_type = 'influxdb'
51:        origin_type = 'prometheus'
88:        origin_type = 'prometheus'
96:        origin_type = 'prometheus'
103:        origin_type = 'prometheus'
131:        origin_type = 'prometheus'
--
./docs/range_request.md
16:    origin_type = 'reverseproxycache'
36:    origin_type = 'reverseproxycache'
--
./docs/metrics.md
22:    * `origin_type` - the type of the configured origin handling the proxy request
30:    * `origin_type` - the type of the configured origin handling the proxy request
38:    * `origin_type` - the type of the configured origin handling the proxy request
46:    * `origin_type` - the type of the configured origin handling the proxy request
55:    * `origin_type` - the type of the configured origin handling the proxy request
62:    * `origin_type` - the type of the configured origin handling the proxy request
--
./docs/negative-caching.md
28:    origin_type = 'rpc'
32:    origin_type = 'rpc'
--
./pkg/util/metrics/metrics.go
145:		[]string{"origin_name", "origin_type", "method", "path", "http_status"},
156:		[]string{"origin_name", "origin_type", "method", "path", "http_status"},
166:		[]string{"origin_name", "origin_type", "method", "path", "http_status"})
175:		[]string{"origin_name", "origin_type", "method", "cache_status", "http_status", "path"},
185:		[]string{"origin_name", "origin_type", "cache_status", "path"},
196:		[]string{"origin_name", "origin_type", "method", "status", "http_status", "path"},
--
./pkg/backends/options/options.go
456:	if metadata.IsDefined("backends", name, "origin_type") {
```

**Comment by pooja-gera** [comment]
Got it, thanks!

**Comment by nananananate** [comment]
In the spirit of Hacktoberfest, I've been helping some projects with their documentation. While the documentation is being updated, if you like, I can implement [Material for MkDocs](https://squidfunk.github.io/mkdocs-material/), which will use Github Pages to host the documentation in your `/docs` folder, creating and updating the documentation website with every change on `/docs` on the master branch.

I know that you guys have some stuff sitting in the `gh-pages` branch, I can help migrate the information there to the `/docs` folder if need be.  

[Here's an example I made](http://docs.coursecake.tisuela.com/)

**Comment by StraysWonderland** [comment]
i would like to contribute and be assigned to this too, if possible.

**Comment by jranson** [comment]
@nananananate that sounds great, and we'd love the help! I created an issue #500 to track this. if you wouldn't mind leaving a comment on that issue, I will then be able to assign it to you. thanks for volunteering!

**Comment by jranson** [comment]
Implemented by @l3g3ndf4i541
