### ISSUE TITLE
Relocate TravisCI jobs to GitHub Actions

### ISSUE THREAD

**Issue by jranson** [tricksterproxy/trickster#496]
TravisCI is no longer meeting our needs, and we'd like to migrate into GitHub actions. We have already the primary release build process moved to Actions, but need to do the same for our basic CI integration tests. This should require no code, just a well-crafted GitHub actions yaml file that replaces the .travis.yml

**Comment by biswaroop1547** [comment]
I would like to work on this, would be great if you could assign this issue to me :)

**Comment by biswaroop1547** [comment]
I just need to replace the .travis.yml file with actions yaml file right? like do I need to make changes anywhere after that to make it work?

**Comment by jranson** [comment]
Once the actions file is added to the project, GitHub automatically picks it up.

In your fork, after you have committed the GitHub actions file, it will automatically start working on your forked/branch. So you can test all of the functionality (commits and PRs) in your own fork to verify the Workflow before submitting the PR back to us.

**Comment by biswaroop1547** [comment]
Thanks! and do I have to replicate that functionalities of travis file in main branch or 2.0x branch? and I need to send a PR to the 2.0x branch right?

**Comment by jranson** [comment]
please PR to `main` thanks! the 2.0.x branch will be removed now that 2.0 development has moved to main (thanks for the reminder! :-)

**Comment by jranson** [comment]
@biswaroop1547 thanks for the PR, everything looks great. I added the `hacktoberfest-accepted` label to your PR so you will get credit towards the contribution rewards. We appreciate it very much!
