### ISSUE TITLE
golang.org/x/sys/unix/gccgo.go:50: error: undefined reference to 'gccgoRealSyscallNoError' (gollvm)

### ISSUE THREAD

**Issue by advancedwebdeveloper** [tricksterproxy/trickster#498]
Hi.
I am using [gollvm](https://go.googlesource.com/gollvm/) and caught this bug:

> $make
> go mod tidy
> go mod vendor
> GOOS= GOARCH=amd64 CGO_ENABLED=0 go build -ldflags "-extldflags '-static' -w -s -X main.applicationBuildTime=2020-10-02T10:31:01+0000 -X main.applicationGitCommitID=eb3fcfcf077d42a3208e50e5ba34b9c49bc7807a -X main.applicationGoVersion=go1.15.2 -X main.applicationGoArch=amd64" -o ./OPATH/trickster -a -v cmd/trickster/*.go
> go build: when using gccgo toolchain, please pass linker flags using -gccgoflags, not -ldflags
> github.com/BurntSushi/toml
> github.com/gorilla/mux
> github.com/tricksterproxy/trickster/pkg/cache/evictionmethods
> github.com/tricksterproxy/trickster/pkg/cache/providers
> github.com/tricksterproxy/trickster/pkg/config/defaults
> github.com/tricksterproxy/trickster/pkg/cache/badger/options
> github.com/tricksterproxy/trickster/pkg/cache/bbolt/options
> github.com/tricksterproxy/trickster/pkg/cache/filesystem/options
> github.com/tricksterproxy/trickster/pkg/cache/index/options
> github.com/tricksterproxy/trickster/pkg/cache/redis/options
> github.com/tricksterproxy/trickster/pkg/cache/status
> github.com/tricksterproxy/trickster/pkg/cache/options
> github.com/tricksterproxy/trickster/pkg/locks
> github.com/philhofer/fwd
> github.com/tricksterproxy/trickster/pkg/cache
> github.com/beorn7/perks/quantile
> github.com/tinylib/msgp/msgp
> github.com/cespare/xxhash/v2
> google.golang.org/protobuf/internal/detrand
> google.golang.org/protobuf/internal/errors
> google.golang.org/protobuf/encoding/protowire
> google.golang.org/protobuf/internal/pragma
> google.golang.org/protobuf/reflect/protoreflect
> google.golang.org/protobuf/reflect/protoregistry
> google.golang.org/protobuf/internal/encoding/messageset
> google.golang.org/protobuf/internal/flags
> google.golang.org/protobuf/internal/strs
> google.golang.org/protobuf/internal/genid
> google.golang.org/protobuf/internal/mapsort
> google.golang.org/protobuf/internal/encoding/text
> google.golang.org/protobuf/internal/set
> google.golang.org/protobuf/internal/fieldsort
> google.golang.org/protobuf/runtime/protoiface
> google.golang.org/protobuf/proto
> google.golang.org/protobuf/internal/descfmt
> google.golang.org/protobuf/internal/descopts
> google.golang.org/protobuf/internal/encoding/defval
> google.golang.org/protobuf/encoding/prototext
> google.golang.org/protobuf/internal/filedesc
> google.golang.org/protobuf/internal/version
> github.com/prometheus/common/internal/bitbucket.org/ww/goautoneg
> github.com/prometheus/common/model
> github.com/prometheus/procfs/internal/fs
> github.com/prometheus/procfs/internal/util
> golang.org/x/sys/internal/unsafeheader
> golang.org/x/sys/unix
> google.golang.org/protobuf/internal/encoding/tag
> google.golang.org/protobuf/internal/impl
> github.com/prometheus/procfs
> github.com/go-logfmt/logfmt
> github.com/go-kit/kit/log
> github.com/go-kit/kit/log/level
> github.com/go-stack/stack
> google.golang.org/protobuf/internal/filetype
> github.com/tricksterproxy/trickster/pkg/backends/rule/options
> github.com/tricksterproxy/trickster/pkg/cache/negative
> google.golang.org/protobuf/runtime/protoimpl
> github.com/tricksterproxy/trickster/pkg/runtime
> github.com/tricksterproxy/trickster/pkg/proxy/urls
> github.com/golang/protobuf/proto
> google.golang.org/protobuf/types/known/anypb
> github.com/golang/protobuf/ptypes/any
> google.golang.org/protobuf/types/known/durationpb
> github.com/golang/protobuf/ptypes/duration
> google.golang.org/protobuf/types/known/timestamppb
> github.com/golang/protobuf/ptypes/timestamp
> github.com/tricksterproxy/trickster/pkg/timeseries
> github.com/golang/protobuf/ptypes
> github.com/prometheus/client_model/go
> github.com/matttproud/golang_protobuf_extensions/pbutil
> github.com/tricksterproxy/trickster/pkg/proxy/headers
> github.com/prometheus/client_golang/prometheus/internal
> github.com/prometheus/common/expfmt
> github.com/tricksterproxy/trickster/pkg/cache/key
> github.com/tricksterproxy/trickster/pkg/proxy/forwarding
> github.com/tricksterproxy/trickster/pkg/proxy/methods
> github.com/tricksterproxy/trickster/pkg/proxy/paths/matching
> github.com/tricksterproxy/trickster/pkg/proxy/request/rewriter/options
> github.com/tricksterproxy/trickster/pkg/proxy/request/rewriter
> github.com/prometheus/client_golang/prometheus
> github.com/tricksterproxy/trickster/pkg/util/strings
> github.com/tricksterproxy/trickster/pkg/proxy/paths/options
> github.com/tricksterproxy/trickster/pkg/proxy/tls/options
> github.com/tricksterproxy/trickster/pkg/backends/options
> github.com/tricksterproxy/trickster/pkg/config/reload/options
> github.com/tricksterproxy/trickster/pkg/tracing/exporters/jaeger/options
> github.com/tricksterproxy/trickster/pkg/tracing/exporters/stdout/options
> github.com/tricksterproxy/trickster/pkg/tracing/options
> github.com/tricksterproxy/trickster/pkg/config
> gopkg.in/natefinch/lumberjack.v2
> github.com/prometheus/client_golang/prometheus/promhttp
> github.com/tricksterproxy/trickster/pkg/logging
> github.com/dgraph-io/badger/options
> github.com/dgraph-io/badger/pb
> github.com/pkg/errors
> golang.org/x/net/internal/timeseries
> github.com/tricksterproxy/trickster/pkg/util/metrics
> golang.org/x/net/trace
> github.com/tricksterproxy/trickster/pkg/cache/metrics
> github.com/tricksterproxy/trickster/pkg/cache/index
> github.com/tricksterproxy/trickster/pkg/cache/memory
> github.com/dgraph-io/badger/y
> github.com/cespare/xxhash
> github.com/dgraph-io/ristretto/z
> github.com/AndreasBriese/bbloom
> github.com/dgraph-io/badger/skl
> github.com/dgraph-io/badger/table
> github.com/dgraph-io/badger/trie
> github.com/dustin/go-humanize
> go.etcd.io/bbolt
> github.com/dgraph-io/badger
> github.com/tricksterproxy/trickster/pkg/cache/bbolt
> github.com/tricksterproxy/trickster/pkg/cache/filesystem
> github.com/go-redis/redis/internal/util
> github.com/go-redis/redis/internal/proto
> github.com/go-redis/redis/internal
> github.com/go-redis/redis/internal/consistenthash
> github.com/go-redis/redis/internal/hashtag
> github.com/go-redis/redis/internal/pool
> github.com/go-redis/redis
> github.com/tricksterproxy/trickster/pkg/cache/badger
> github.com/tricksterproxy/trickster/pkg/config/reload
> github.com/tricksterproxy/trickster/pkg/backends
> github.com/tricksterproxy/trickster/pkg/proxy/context
> go.opentelemetry.io/otel/api/propagation
> go.opentelemetry.io/otel/codes
> go.opentelemetry.io/otel/internal
> go.opentelemetry.io/otel/label
> go.opentelemetry.io/otel/api/trace
> github.com/tricksterproxy/trickster/pkg/tracing
> github.com/tricksterproxy/trickster/pkg/proxy/request
> github.com/tricksterproxy/trickster/pkg/proxy/handlers
> github.com/felixge/httpsnoop
> github.com/gorilla/handlers
> github.com/tricksterproxy/trickster/pkg/proxy/errors
> github.com/tricksterproxy/trickster/pkg/proxy/tls
> golang.org/x/net/netutil
> github.com/tricksterproxy/trickster/pkg/proxy/listener
> github.com/tricksterproxy/trickster/pkg/parsing/token
> github.com/tricksterproxy/trickster/pkg/parsing/lex
> github.com/tricksterproxy/trickster/pkg/parsing
> github.com/tricksterproxy/trickster/pkg/parsing/lex/sql
> github.com/tricksterproxy/trickster/pkg/parsing/sql
> github.com/tricksterproxy/trickster/pkg/proxy
> github.com/golang/snappy
> github.com/tricksterproxy/trickster/pkg/proxy/params
> github.com/tricksterproxy/trickster/pkg/util/md5
> github.com/tricksterproxy/trickster/pkg/proxy/ranges/byterange
> go.opentelemetry.io/otel/api/correlation
> go.opentelemetry.io/otel/api/unit
> go.opentelemetry.io/otel/api/metric
> github.com/tricksterproxy/trickster/pkg/cache/redis
> go.opentelemetry.io/otel
> go.opentelemetry.io/otel/api/metric/registry
> github.com/tricksterproxy/trickster/pkg/cache/registration
> go.opentelemetry.io/otel/api/global/internal
> go.opentelemetry.io/otel/semconv
> go.opentelemetry.io/otel/api/global
> github.com/tricksterproxy/trickster/pkg/timeseries/sqlparser
> go.opentelemetry.io/contrib/instrumentation/net/http/httptrace
> github.com/tricksterproxy/trickster/pkg/util/fnv
> github.com/tricksterproxy/trickster/pkg/timeseries/dataset
> github.com/tricksterproxy/trickster/pkg/tracing/span
> github.com/tricksterproxy/trickster/pkg/proxy/engines
> github.com/tricksterproxy/trickster/pkg/backends/clickhouse/model
> github.com/tricksterproxy/trickster/pkg/util/regexp/matching
> github.com/tricksterproxy/trickster/pkg/util/timeconv
> github.com/tricksterproxy/trickster/pkg/backends/influxdb/model
> github.com/tricksterproxy/trickster/pkg/backends/irondb/common
> github.com/tricksterproxy/trickster/pkg/backends/irondb/model
> github.com/tricksterproxy/trickster/pkg/backends/clickhouse
> github.com/tricksterproxy/trickster/pkg/backends/influxdb
> github.com/tricksterproxy/trickster/pkg/backends/irondb
> github.com/tricksterproxy/trickster/pkg/backends/prometheus
> github.com/tricksterproxy/trickster/pkg/backends/prometheus/model
> github.com/tricksterproxy/trickster/pkg/backends/reverseproxycache
> github.com/tricksterproxy/trickster/pkg/util/base64
> github.com/tricksterproxy/trickster/pkg/util/sha1
> github.com/tricksterproxy/trickster/pkg/backends/rule
> github.com/tricksterproxy/trickster/pkg/backends/types
> github.com/tricksterproxy/trickster/pkg/util/middleware
> github.com/tricksterproxy/trickster/pkg/tracing/errors
> github.com/tricksterproxy/trickster/pkg/routing
> github.com/apache/thrift/lib/go/thrift
> go.opentelemetry.io/otel/sdk/instrumentation
> go.opentelemetry.io/otel/sdk/resource
> google.golang.org/grpc/codes
> go.opentelemetry.io/otel/sdk/export/trace
> go.opentelemetry.io/otel/internal/trace/parent
> go.opentelemetry.io/otel/sdk
> go.opentelemetry.io/otel/sdk/internal
> go.opentelemetry.io/otel/sdk/trace/internal
> go.opentelemetry.io/otel/sdk/trace
> golang.org/x/sync/semaphore
> google.golang.org/api/support/bundler
> github.com/tricksterproxy/trickster/pkg/tracing/exporters/noop
> go.opentelemetry.io/otel/sdk/export/metric/aggregation
> go.opentelemetry.io/otel/sdk/export/metric
> go.opentelemetry.io/otel/internal/metric
> go.opentelemetry.io/otel/sdk/metric/aggregator
> go.opentelemetry.io/otel/sdk/metric
> go.opentelemetry.io/otel/sdk/metric/controller/time
> go.opentelemetry.io/otel/sdk/metric/controller/push
> go.opentelemetry.io/otel/exporters/trace/jaeger/internal/gen-go/jaeger
> go.opentelemetry.io/otel/sdk/metric/processor/basic
> go.opentelemetry.io/otel/sdk/metric/aggregator/array
> github.com/DataDog/sketches-go/ddsketch
> go.opentelemetry.io/otel/sdk/metric/aggregator/ddsketch
> go.opentelemetry.io/otel/sdk/metric/aggregator/histogram
> go.opentelemetry.io/otel/exporters/trace/jaeger
> go.opentelemetry.io/otel/sdk/metric/aggregator/minmaxsumcount
> go.opentelemetry.io/otel/sdk/metric/aggregator/sum
> go.opentelemetry.io/otel/sdk/metric/selector/simple
> github.com/tricksterproxy/trickster/pkg/tracing/exporters/jaeger
> go.opentelemetry.io/otel/exporters/stdout
> github.com/openzipkin/zipkin-go/model
> go.opentelemetry.io/otel/exporters/trace/zipkin
> github.com/tricksterproxy/trickster/pkg/tracing/exporters/stdout
> github.com/tricksterproxy/trickster/pkg/tracing/providers
> github.com/tricksterproxy/trickster/pkg/tracing/exporters/zipkin
> github.com/tricksterproxy/trickster/pkg/tracing/registration
> command-line-arguments
> # command-line-arguments
> /home/oceanfis81/go_projects/trickster/vendor/golang.org/x/sys/unix/gccgo.go:55: error: undefined reference to 'gccgoRealSyscall'
> /home/oceanfis81/go_projects/trickster/vendor/golang.org/x/sys/unix/gccgo.go:30: error: undefined reference to 'gccgoRealSyscall'
> /home/oceanfis81/go_projects/trickster/vendor/golang.org/x/sys/unix/gccgo.go:23: error: undefined reference to 'gccgoRealSyscallNoError'
> /home/oceanfis81/go_projects/trickster/vendor/golang.org/x/sys/unix/gccgo.go:37: error: undefined reference to 'gccgoRealSyscall'
> /home/oceanfis81/go_projects/trickster/vendor/golang.org/x/sys/unix/gccgo.go:44: error: undefined reference to 'gccgoRealSyscall'
> /home/oceanfis81/go_projects/trickster/vendor/golang.org/x/sys/unix/gccgo.go:50: error: undefined reference to 'gccgoRealSyscallNoError'
> make: *** [Makefile:57: build] Error 2
> 

CC @thanm @cherrymui @ianlancetaylor

**Comment by jranson** [comment]
HI, thanks for this report. Unfortunately this is in a vendor package and you are using a non-standard/experimental go compiler, so we are not able to help you with this. It's possible you can get it working by changing the build flags but we can't make changes to the main `build` action to support an experiment. I would recommend trying it with CGO_ENABLED=1, and if that works, we'll gladly accept a PR with an additional make action (e.g., `make-gollvm`).

**Comment by advancedwebdeveloper** [comment]
CC @thanm @cherryui
BCC @ianlancetaylor

**Comment by ianlancetaylor** [comment]
This is happening because of the `CGO_ENABLED=0` set by the `Makefile`.  This causes a bug in the go tool.  I filed https://golang.org/issue/41758 aka golang/go#41758.

If you set `CGO_ENABLED=1` before running `make`, the code builds.

(By the way, @advancedwebdeveloper, GitHub does not support BCC.  A BCC is exactly the same as a CC.)
