### ISSUE TITLE
1.1 performance regression

### ISSUE THREAD

**Issue by BertHartm** [tricksterproxy/trickster#511]
It seems like when we load test trickster with a prometheus backend, that 1.1 has a reasonably large performance regression as compared to 1.0

both 1.1.2 and 1.1.3 seems to max out at around 100 requests per second when we load test it. 1.0 doesn't seem to get throttled in the same way and can go to several hundred (haven't tried higher yet). We also see much higher cpu and memory usage for 1.1.

We're trying about 15 different queries set to query over the last hour.

**Comment by jranson** [comment]
Hey Bert, thanks for reporting this. Would you be able to give a bit more information (e.g., cache type and tsdb type). Also if it would be possible to capture some pprof samples (particularly the goroutine sample, but all would be welcomed), that would be really helpful in troubleshooting. Thanks again.

**Comment by jranson** [comment]
btw, if you are not a pprof master, you can go to http://trickster:8481/debug/pprof where each of the links are downloadable artifacts that help us with the performance profiling.

**Comment by BertHartm** [comment]
Hey, not sure what you mean by cache type?

The TSDB is prometheus (though we remote read from m3db). we have it set to not cache the last 5 minutes.

here's the text of the heap endpoint, as well as a cpu profile and binary heap:

[trickster_heap.out.gz](https://github.com/tricksterproxy/trickster/files/5461001/trickster_heap.out.gz)
[trickster_cpu.out.gz](https://github.com/tricksterproxy/trickster/files/5461002/trickster_cpu.out.gz)
[heap_debug.txt.gz](https://github.com/tricksterproxy/trickster/files/5461003/heap_debug.txt.gz)

**Comment by jranson** [comment]
we support memory, filesystem, redis, etc. for where the actual cached data is stored and retrieved by trickster. The default is memory, so if you have not configured anything else, that is what your deployment is using.  would you be able to attach the goroutine pprof for us? that one is what lets us know where time is being spent. Thanks again!

**Comment by BertHartm** [comment]
sorry, yeah we're using `filesystem` for the cache type.

here are the goroutines and allocs from a different instance that was slightly less stressed than the other profiles above:

[allocs_debug.txt.gz](https://github.com/tricksterproxy/trickster/files/5461058/allocs_debug.txt.gz)
[goroutines_debug_2.txt.gz](https://github.com/tricksterproxy/trickster/files/5461059/goroutines_debug_2.txt.gz)
[goroutines_debug.txt.gz](https://github.com/tricksterproxy/trickster/files/5461060/goroutines_debug.txt.gz)

**Comment by LimitlessEarth** [comment]
Some CPU sampling would be useful as well. That may get you to the meat of what you are looking for pretty quickly.
```
curl http://trickster:8481/debug/pprof/profile\?seconds\=300 -o profile.out
```
This will give us/you a good representation of what the CPU is spending it's time executing. 
```
go tool pprof -http=":8081" /path/to/binary profile.out
```

**Comment by LimitlessEarth** [comment]
Ideally while there is load which is showing the symptoms you are describing.

**Comment by BertHartm** [comment]
Hi @LimitlessEarth , there's a cpu profile in the first set of files (trickster_cpu.out.gz). It's only 5 seconds worth of data though.

It does seem to be spending all of it's time in the DeltaProxyCacheRequest based on the cpu and memory profiles.

**Comment by jranson** [comment]
@BertHartm I think we have this one nailed down. We're working on a design pattern that will achieve the locking pattern we need without suffering performance under load and should have a patch for 1.1 in the next few days.

**Comment by BertHartm** [comment]
@jranson thanks. let me know if you have a PR and want us to test.

**Comment by jranson** [comment]
@BertHartm sorry for the delay in getting back to you on this. We have rolled a release candidate `v1.1.4-rc1` build that hopefully will address this. We'd love to get some feedback from you on it. The build is available in the releases section [here on GitHub](https://github.com/tricksterproxy/trickster/releases/tag/v1.1.4-rc1), and at tag `tricksterproxy/trickster:1.1.4-rc1` on [Docker Hub](https://hub.docker.com/layers/130348090/tricksterproxy/trickster/1.1.4-rc1/images/sha256-f78384f5df3b28177bb18161b592040bd7173acb02632ba315baa9199edfcd67). Thanks for your help!

**Comment by jranson** [comment]
@BertHartm just wanted to check and see if you were able to give this a spin? Thanks for your help!

**Comment by jranson** [comment]
@BertHartm we went ahead and pushed the 1.1.4 GA release, which includes improves in the areas you identified. If you are still having issues please reopen. Thanks!
