### ISSUE TITLE
Possible to write a rule that has a case relying on complex regex or some kind of scripting module?

### ISSUE THREAD

**Issue by WesleyDavid** [tricksterproxy/trickster#515]
I'm looking at incoming requests with [rules](https://github.com/tricksterproxy/trickster/blob/main/docs/rule.md). In the case `matches` statement, it looks like it's only a list of strings that match the [input type operation](https://github.com/tricksterproxy/trickster/blob/main/docs/rule.md#input_type-permitted-values-and-operations) that was set up in the rule. What I think I need is some logic right in that `matches` statement, but instead it's restricted to a list of strings that match the operation in the rule. Is there any means of inserting logic into a rule case, such as with more complex regex?

Ultimately what it feels like I need is a processing engine of some kind. This feels like problems that have been solved in the past with Nginx or HAProxy and their Lua module. In fact, at the moment I'm considering the need for a thin proxy layer in front of Trickster (possibly using proxy.py) to grab queries and make more complex deductions from the query before routing them to the proper Trickster route. At that point Trickster is purely being used for cacheing, and routing has been pulled up to another application. Is a module system for supporting scripting languages on the roadmap?

For more context, the _specific_ problem I'm looking to solve is routing InfluxQL / Flux queries that range over certain time periods to different retention policies or origins in InfluxDB. In natural language: "If this query's range starts and ends within any points in the last 48 hours, go here. If it starts no sooner than one week ago and ends no later than two weeks ago rewrite the query to have this specific retention policy. If the start and end are over 30 days ago, rewrite the whole query to a different origin."

**Comment by jranson** [comment]
closing as implemented - wesley, definitely re-open or file another issue if you find any problems w/ the rmatch capability
