### ISSUE TITLE
Prometheus always works on “cacheStatus=purge”

### ISSUE THREAD

**Issue by guilongyang** [tricksterproxy/trickster#521]
hello,my friend
   the config about the prometheus is:

   [origins.default]
    origin_type = "prometheus"
    origin_url = "http://prometheus-center.monitoring.svc.cluster.local:9090"
    timeout_secs = 180
    keep_alive_timeout_secs = 300
    max_idle_conns = 20
    cache_name = "default"
    cache_key_prefix = "prometheus-center.monitoring.svc.cluster.local:9090"
    health_check_upstream_path = "/api/v1/query"
    health_check_verb = "GET"
    health_check_query = "query=up"
    timeseries_retention_factor = 1024
    timeseries_eviction_method = "oldest"
    backfill_tolerance_secs = 0
    negative_cache_name = "default"
    timeseries_ttl_secs = 21600
    fastforward_ttl_secs = 15
    max_ttl_secs = 86400
    revalidation_factor = 2.0
    max_object_size_bytes = 524288
    compressable_types = ["text/html", "text/javascript", "text/css", "text/plain", "text/xml", "text/json", "application/json", "application/javascript", "application/xml"]
    tracing_name = "default"
    rule_name = ""
    req_rewriter_name = "remove-no-cache"
    forwarded_headers = "standard"
    is_default = true
    fast_forward_disable = false
    path_routing_disabled = false
    require_tls = false
    multipart_ranges_disabled = false
    dearticulate_upstream_ranges = false
    [origins.default.health_check_headers]
    [origins.default.paths]
      [origins.default.paths."/-GET-POST"]
        path = "/"
        match_type = "prefix"
        handler = "proxy"
        methods = ["GET", "POST"]
        cache_key_params = []
        cache_key_headers = []
        cache_key_form_fields = []
        response_code = 0
        response_body = ""
        collapsed_forwarding = ""
        req_rewriter_name = ""
        no_metrics = false
      [origins.default.paths."/api/v1/-GET-POST"]
        path = "/api/v1/"
        match_type = "prefix"
        handler = "proxy"
        methods = ["GET", "POST"]
        cache_key_params = []
        cache_key_headers = []
        cache_key_form_fields = []
        response_code = 0
        response_body = ""
        collapsed_forwarding = ""
        req_rewriter_name = ""
        no_metrics = false
      [origins.default.paths."/api/v1/alertmanagers-GET"]
        path = "/api/v1/alertmanagers"
        match_type = "exact"
        handler = "proxycache"
        methods = ["GET"]
        cache_key_params = []
        cache_key_headers = []
        cache_key_form_fields = []
        response_code = 0
        response_body = ""
        collapsed_forwarding = ""
        req_rewriter_name = ""
        no_metrics = false
        [origins.default.paths."/api/v1/alertmanagers-GET".response_headers]
          Cache-Control = "s-maxage=30"
      [origins.default.paths."/api/v1/alerts-GET"]
        path = "/api/v1/alerts"
        match_type = "exact"
        handler = "proxycache"
        methods = ["GET"]
        cache_key_params = []
        cache_key_headers = []
        cache_key_form_fields = []
        response_code = 0
        response_body = ""
        collapsed_forwarding = ""
        req_rewriter_name = ""
        no_metrics = false
        [origins.default.paths."/api/v1/alerts-GET".response_headers]
          Cache-Control = "s-maxage=30"
      [origins.default.paths."/api/v1/label/-GET"]
        path = "/api/v1/label/"
        match_type = "prefix"
        handler = "proxycache"
        methods = ["GET"]
        cache_key_params = []
        cache_key_headers = []
        cache_key_form_fields = []
        response_code = 0
        response_body = ""
        collapsed_forwarding = ""
        req_rewriter_name = ""
        no_metrics = false
        [origins.default.paths."/api/v1/label/-GET".response_headers]
          Cache-Control = "s-maxage=30"
      [origins.default.paths."/api/v1/labels-GET-POST"]
        path = "/api/v1/labels"
        match_type = "exact"
        handler = "proxycache"
        methods = ["GET", "POST"]
        cache_key_params = []
        cache_key_headers = []
        cache_key_form_fields = []
        response_code = 0
        response_body = ""
        collapsed_forwarding = ""
        req_rewriter_name = ""
        no_metrics = false
        [origins.default.paths."/api/v1/labels-GET-POST".response_headers]
          Cache-Control = "s-maxage=30"
      [origins.default.paths."/api/v1/query-GET-POST"]
        path = "/api/v1/query"
        match_type = "exact"
        handler = "query"
        methods = ["GET", "POST"]
        cache_key_params = ["query", "time"]
        cache_key_headers = []
        cache_key_form_fields = []
        response_code = 0
        response_body = ""
        collapsed_forwarding = ""
        req_rewriter_name = ""
        no_metrics = false
        [origins.default.paths."/api/v1/query-GET-POST".response_headers]
          Cache-Control = "s-maxage=30"
      [origins.default.paths."/api/v1/query_range-GET-POST"]
        path = "/api/v1/query_range"
        match_type = "exact"
        handler = "query_range"
        methods = ["GET", "POST"]
        cache_key_params = ["query", "step"]
        cache_key_headers = []
        cache_key_form_fields = []
        response_code = 0
        response_body = ""
        collapsed_forwarding = ""
        req_rewriter_name = ""
        no_metrics = false
        [origins.default.paths."/api/v1/query_range-GET-POST".response_headers]
          Cache-Control = "s-maxage=21600"
      [origins.default.paths."/api/v1/rules-GET"]
        path = "/api/v1/rules"
        match_type = "exact"
        handler = "proxycache"
        methods = ["GET"]
        cache_key_params = []
        cache_key_headers = []
        cache_key_form_fields = []
        response_code = 0
        response_body = ""
        collapsed_forwarding = ""
        req_rewriter_name = ""
        no_metrics = false
        [origins.default.paths."/api/v1/rules-GET".response_headers]
          Cache-Control = "s-maxage=30"
      [origins.default.paths."/api/v1/series-GET-POST"]
        path = "/api/v1/series"
        match_type = "exact"
        handler = "series"
        methods = ["GET", "POST"]
        cache_key_params = ["match[]", "start", "end"]
        cache_key_headers = []
        cache_key_form_fields = []
        response_code = 0
        response_body = ""
        collapsed_forwarding = ""
        req_rewriter_name = ""
        no_metrics = false
        [origins.default.paths."/api/v1/series-GET-POST".response_headers]
          Cache-Control = "s-maxage=30"
      [origins.default.paths."/api/v1/status-GET"]
        path = "/api/v1/status"
        match_type = "prefix"
        handler = "proxycache"
        methods = ["GET"]
        cache_key_params = []
        cache_key_headers = []
        cache_key_form_fields = []
        response_code = 0
        response_body = ""
        collapsed_forwarding = ""
        req_rewriter_name = ""
        no_metrics = false
        [origins.default.paths."/api/v1/status-GET".response_headers]
          Cache-Control = "s-maxage=30"
      [origins.default.paths."/api/v1/targets-GET"]
        path = "/api/v1/targets"
        match_type = "exact"
        handler = "proxycache"
        methods = ["GET"]
        cache_key_params = []
        cache_key_headers = []
        cache_key_form_fields = []
        response_code = 0
        response_body = ""
        collapsed_forwarding = ""
        req_rewriter_name = ""
        no_metrics = false
        [origins.default.paths."/api/v1/targets-GET".response_headers]
          Cache-Control = "s-maxage=30"
      [origins.default.paths."/api/v1/targets/metadata-GET"]
        path = "/api/v1/targets/metadata"
        match_type = "exact"
        handler = "proxycache"
        methods = ["GET"]
        cache_key_params = ["match_target", "metric", "limit"]
        cache_key_headers = []
        cache_key_form_fields = []
        response_code = 0
        response_body = ""
        collapsed_forwarding = ""
        req_rewriter_name = ""
        no_metrics = false
        [origins.default.paths."/api/v1/targets/metadata-GET".response_headers]
          Cache-Control = "s-maxage=30"
    [origins.default.tls]
      full_chain_cert_path = ""
      private_key_path = ""
      insecure_skip_verify = false
      client_cert_path = ""
      client_key_path = ""
[request_rewriters]
  [request_rewriters.remove-no-cache]
    instructions = [["header", "delete", "Cache-Control", "no-store"], ["header", "delete", "Cache-Control", "no-cache"], ["header", "delete", "Pragma"]]

when i reqeust this "http://xxxxx:8480/api/v1/query_range?query=vm_cpu_busy%7Bresource_id%3D%2239ddf344-bf21-44ad-a793-0ac1e8ccd1c9%22%7D&start=1608099032.594&end=1608703832.594&step=2419&_=1608703690822"

the logs tell me that it does not use cache
the log is 

time=2020-12-25T07:41:58.548638779Z app=trickster caller=proxy/engines/access_logs.go:27 level=debug event="upstream request" method=GET size=4559 originName=default originType=prometheus userAgent=PostmanRuntime/6.4.1 code=200 durationMS=4 handlerName=query_range uri="http://prometheus-center.monitoring.svc.cluster.local:9090/api/v1/query_range?query=vm_cpu_busy%7Bresource_id%3D%2239ddf344-bf21-44ad-a793-0ac1e8ccd1c9%22%7D&start=1608099032.594&end=1608703832.594&step=2419&_=1608703690822"
time=2020-12-25T07:41:58.549608569Z app=trickster caller=runtime/asm_amd64.s:1373 level=debug event="memorycache cache store" ttl=6h0m0s is_direct=true cacheKey=prometheus-center.monitoring.svc.cluster.local:9090.dpc.441f4731bf71695c54e297f7838c66e9 length=0
time=2020-12-25T07:41:58.550814684Z app=trickster caller=proxy/engines/deltaproxycache.go:465 level=debug event="delta routine completed" cacheKey=prometheus-center.monitoring.svc.cluster.local:9090.dpc.441f4731bf71695c54e297f7838c66e9 cacheStatus=purge reqStart=1608098721 reqEnd=1608703471

is some thing wrong with my config?
Expect your reply
best regards

**Comment by jranson** [comment]
hi @guilongyang , it looks like the reason this is not being cached is because you are using a step of `step=2419` in your postman request. You would need to use an identical step to what is being used by your dashboard application, which is generally a multiple of 15. The step value is used to calculate the query's key, so any time you change it, you will be creating a new cache entry, as with your above example.
