### ISSUE TITLE
Step Boundaries on InfluxDB

### ISSUE THREAD

**Issue by nachopv** [tricksterproxy/trickster#523]
Hi 
I'm testing suitability of Influx for our use case and I'm observing that when moving backwards ( i.e. when moving  from last 5 minutes to last 15 minutes  in grafana ) , the data shown is not always complete

Debugging the data i do see i do have 2 points in the same minute
![image](https://user-images.githubusercontent.com/70150083/105618524-7dd77480-5de8-11eb-96ce-4abcc7b97c49.png)

Checking step boundaries documentation , i understand  that as long as my query is aggregating timeframes by 1m , no matter the exact second in the boundaries, they will rounded to cover the whole minute

However , as you can see in the following screenshot is not doing so
![image](https://user-images.githubusercontent.com/70150083/105618547-cee76880-5de8-11eb-84bb-d01f881d1e2c.png)

The only way to retrieve the complete data is to  actually  extend the timeframe to cover both points
![image](https://user-images.githubusercontent.com/70150083/105618577-41f0df00-5de9-11eb-868f-d1a56472fe36.png)

Am i missunderstanding Step Boundaries logic oris this a non expected behaviour?

**Comment by nachopv** [comment]
We proceed to closure as long we do think is addressed with the following PR
https://github.com/tricksterproxy/trickster/pull/525

**Comment by jranson** [comment]
@nachopv thanks! please re-open if you find this is still not working and we'll take a look.
