### ISSUE TITLE
Handling of cancelled client requests

### ISSUE THREAD

**Issue by genzgd** [tricksterproxy/trickster#571]
This is basically a question.  From what I can tell, if you refresh/reload a Grafana dashboard it will cancel outstanding database requests.  If Trickster in turn has long running requests to the backend database, are those proxied requests also cancelled?

**Comment by jranson** [comment]
Hi Geoff  - I believe this works as you describe, since the inbound request's context is associated with the upstream request
and should abort when it is canceled by the client. I will verify this and let you know for sure.

**Comment by genzgd** [comment]
Thanks -- I'm trying to figure out at what layer in our proxying flow that the request is not being cancelled.  People push "refresh" on Grafana but somehow the original slow queries are still being processed by ClickHouse.  But I assume this behavior is important for other back ends as well.

**Comment by genzgd** [comment]
After some more testing this works exactly as you expected/described.  Thanks!
